# Copy this file as config.yml
# 
# For paths, you could use '~' or $HOME
# Also the following variables are available to be used
# - $root: points to the directory containing this config file.
#

profile:
	name: profile_name
	# path to the directory containing {profile_name}.info
	path: /path/to/profile/file
	# could be either file name within profile or an abosulte path
	makefile: stub.make

build:
	# path to build directory
	path: /path/to/docroot
	# If set, a symlink to sites/default/files will be created
	files: /path/to/public-files
	# If set true, will create a symblink to the repo (for live dev)
	symlink_to_profile: false 

install:
	base_profile: standard
	# As in --db-url in `drush si` 
	db_url: mysql://drupaluser@127.0.0.1:3306/database_name
	db_dump: $root/db/dump.sql
	features_revert_all: true
	print_uli: false
	# If specified will be executed in $config_profile_path
	post_script: $root/post-install.sh
