# Copy this file as config.yml
# 
# For paths, you could use '~' or $HOME
# Also the following variables are available to be used
# - $root: points to the directory containing this config file.
#

drupal:
	url: http://localhost/
	docroot: _build
	# As in --db-url in `drush site-install`
	db_url: mysql://drupaluser@127.0.0.1:3306/database_name

profile:
	name: profile_name
	# path to the directory containing {profile_name}.info
	path: /path/to/profile/file

install:
	# if specified will be installed first and $config_profile_name will be installed on top of it. defaults to empty
	base_profile: standard
	settingsphp:
		# If true, the database credentials would be written to a php file which is specififed by the config below
		generate: true
		# Optional, settings.php by default. If you do not want settings.php to be generated include a separate file there and put the filename here
		filename: settings.php

makefile:
	# path to makefile to be used by drush.
	path: stub.make

deploy:
	docroot: makefile
	profile: symlink
	install:
		print_uli: false

# build:
# 	# this path will be used as docroot using symlink [if specified profile_makefile will be ignored]
# 	source: /path/to/source/code
# 	# If set, a symlink to sites/default/files will be created
# 	files: /path/to/public-files
# 	# If set true, will create a symblink to the repo (for live dev)
# 	symlink_to_profile: false

# install:
# 	db_dump: $root/db/dump.sql
# 	features_revert_all: true
# 	# If specified will be executed in $config_profile_path
# 	post_script: $root/post-install.sh
